<?php
/** @var \Mirasvit\Banner\Block\Placeholder\PopupRenderer $block */
$placeholder = $block->getPlaceholder();
$widgetData  = $block->getPopupConfig();
$banners     = $block->getBanners();

if (!$banners || !count($banners)) {
    return;
}
?>
<div data-banner-renderer="<?= $placeholder->getId() ?>" class="mstBanner-placeholder__popupRenderer <?= $block->getPositionClass() ?>">
    <div class="mstBanner__close" data-element="close">&times;</div>
    <?php foreach ($banners as $banner): ?><?= $block->getBannerHtml($banner) ?><?php endforeach ?>
</div>

<script type="text/x-magento-init"><?= $block->jsonEncode([
        '[data-banner-renderer="' . $placeholder->getId() . '"]' => [
            'Mirasvit_Banner/js/placeholder/popup-renderer' => $widgetData,
        ],
    ]) ?></script>

