<?php
/**
 * Copyright © 2013-2017 Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

/** @var $block Magento\Wishlist\Block\Catalog\Product\ProductList\Item\AddTo\Wishlist */
?>
<?php if ($block->getWishlistHelper()->isAllow()) : ?>
    <a href="#"
       class="action towishlist"
       title="<?= $block->escapeHtml(__('Add to Wish List')); ?>"
       aria-label="<?= $block->escapeHtml(__('Save')); ?>"
       data-post='<?= /* @noEscape */ $block->getAddToWishlistParams($block->getProduct()); ?>'
       data-action="add-to-wishlist"
       role="button">
        <span><?= $block->escapeHtml(__('Add to Wish List')) ?></span>
    </a>
<?php endif; ?>
