<?php
/**
 * Copyright © 2013-2017 Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

?>
<?php /* @var $captcha \Magento\Captcha\Model\DefaultModel */ ?>
<?php /* @var $block \Magento\Captcha\Block\Captcha\DefaultCaptcha */ ?>
<?php $captcha = $block->getCaptchaModel();
/** @var bool $validationEnabled */
$validationEnabled = $block->hasData('frontend_validation') ? $block->getData('frontend_validation') : true;
$inputName = $block->escapeHtmlAttr(\Magento\Captcha\Helper\Data::INPUT_NAME_FIELD_VALUE);
$loaderUrl = $block->escapeUrl($block->getViewFileUrl('images/loader-2.gif'));
$note = $block->escapeHtml(__('<strong>Attention</strong>: Captcha is case sensitive.'), ['strong']);
?>
<div class="field captcha <?php if ($validationEnabled): ?> required<?php endif; ?>"
     role="<?php /* @escapeNotVerified */ echo $block->getFormId()?>">
    <div class="control captcha">
        <input
            placeholder="<?php /* @escapeNotVerified */ echo __('Please type the letters below')?>"
            name="<?= /* @noEscape */ $inputName ?>[<?= $block->escapeHtmlAttr($block->getFormId()) ?>]"
            type="text"
            class="input-text<?php if ($validationEnabled): ?> required-entry<?php endif; ?>"
            <?php if ($validationEnabled): ?>data-validate="{required:true}"<?php endif; ?>
            id="captcha_<?php /* @escapeNotVerified */ echo $block->getFormId() ?>" />
        <div class="nested">
            <div class="field captcha no-label"
                 data-captcha="<?php /* @escapeNotVerified */ echo $block->getFormId()?>"
                 id="captcha-container-<?php /* @escapeNotVerified */ echo $block->getFormId()?>"
                 data-mage-init='{"captcha":{"url": "<?php /* @escapeNotVerified */ echo $block->getRefreshUrl()?>",
                                            "imageLoader": "<?= /* @noEscape */ $loaderUrl ?>",
                                             "type": "<?php /* @escapeNotVerified */ echo $block->getFormId() ?>"}}'>
                <div class="control captcha-image">
                    <img alt="<?php /* @escapeNotVerified */ echo __('Please type the letters below')?>"
                         class="captcha-img"
                         height="<?php /* @escapeNotVerified */ echo $block->getImgHeight() ?>"
                         src="<?php /* @escapeNotVerified */ echo $captcha->getImgSrc() ?>"/>
                    <button type="button" class="action reload captcha-reload" title="<?php /* @escapeNotVerified */ echo __('Reload captcha') ?>"><span><?php /* @escapeNotVerified */ echo __('Reload captcha') ?></span></button>
                </div>
            </div>
            <?php if ($captcha->isCaseSensitive()) :?>
                <div class="captcha-note note"><?= /* @noEscape */ $note ?></div>
            <?php endif; ?>
        </div>
    </div>
</div>
