<?php
/** \Custom\City\Block\City $block */
if($block->isEnabled()):
    $is_state_available = $block->isStateAvailable();
    $isShippingRateEnabled = $block->isShippingRateEnabled();
    $cityUrl = $block->getUrl('city/index/cities');
    $zip_url = $block->getUrl('city/index/zips');
    $city_title = __('City not in list');
    $city_link = $block->cityNotInList();
    if($block->cityNotInListTitle() !== ""){
        $city_title = __($block->cityNotInListTitle());
    }
    $zip_title = __('Zip not in list');
    $zip_link = $block->zipNotInList();
    if($block->zipNotInListTitle() !== ""){
        $zip_title = __($block->zipNotInListTitle());
    }
    ?>
    <script type="text/javascript">
        var data_city_link="<?php echo $city_link;?>";
        var data_city_title="<?php echo $city_title;?>";
        var data_zip_link="<?php echo $zip_link;?>";
        var data_zip_title="<?php echo $zip_title;?>";
        var data_city_url="<?php echo $cityUrl;?>";
        var data_zip_url="<?php echo $zip_url;?>";
        var loading_url = "<?php echo $this->getViewFileUrl('Custom_City::images/loader-1.gif');?>";
        var is_state_available = "<?php echo (int)$is_state_available;?>";
        var city_option_title = "<?php echo $block->cityOptionTitle();?>";
        var zip_option_title = "<?php echo $block->zipOptionTitle();?>";
        var isShippingRateEnabled = "<?php echo $isShippingRateEnabled;?>";
    </script>
<?php endif; ?>
<script type="text/javascript">
    var is_city_enabled = "<?php echo $block->isEnabled();?>";
</script>
